#!/usr/bin/env bash

echo "Setting up your Mac..."

# Check for Homebrew and abort if we don't have it
if ! type brew >/dev/null 2>/dev/null; then
  echo "You need to run the remote-install.sh script first, aborting..."
  exit 1
fi

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until setup has finished
while true; do
  sudo -n true
  sleep 60
  kill -0 "$$" || exit
done 2>/dev/null &

# Hide "last login" line when starting a new terminal session
echo "Creating Hushlogin"
touch $HOME/.hushlogin

# run mac software update
echo "Updating Your Mac"
sudo softwareupdate -i -a


################################################################################
#
# Brewfile
#
################################################################################
echo "Brewing..."
brew update
brew tap homebrew/bundle
brew bundle --file=~/.config/dotfiles/prefs/Homebrew/Brewfile
brew cleanup


################################################################################
#
# PHP related packages & software
#
################################################################################

# add composer to PATH for the duration of this installer
echo "Adding Composer To PATH"
export PATH=$PATH:~/.composer/vendor/bin

# Laravel Installer, Valet etc.
echo "Creating Laravel Installers"
composer global require laravel/installer laravel/spark-installer laravel/valet

# run valet installer
echo "Installing Laravel Valet"
valet install

echo "Cloning custom Global-Env Valet driver"
cd ~/.config/valet/Drivers
git clone https://github.com/madsem/valet-global-env.git
cd ~

# installing PHP extensions
echo "Install imagick, accepting defaults"
yes '' | pecl install -f imagick

echo "Install memcached, accepting defaults"
yes '' | pecl install -f memcached

echo "Install xdebug, accepting defaults"
yes '' | pecl install -f xdebug

echo "Install Phpredis, accepting defaults"
yes '' | pecl install -f redis


################################################################################
#
# Install Visual Studio Code Extensions
#
################################################################################
echo "Installing VS Code Extensions"
for EXT in $(cat ~/.config/dotfiles/prefs/VisualStudioCode/extensions); do
  code --install-extension $EXT
done


################################################################################
#
# Fish Shell
#
################################################################################
echo "Making Fish The Default Shell..."
if ! sudo cat /etc/shells | grep -xqFe "$(which fish)"; then
  echo $(which fish) | sudo tee -a /etc/shells
  sudo chsh -s $(which fish) ${USER}
fi


################################################################################
#
# iTerm2
#
################################################################################
echo "Installing iTerm2 Shell Integration"
curl -L https://iterm2.com/shell_integration/fish \
  -o ~/.iterm2_shell_integration.fish


################################################################################
#
# Creating directories & Files
#
################################################################################
echo "Creating ~/Sites"
if [ ! -d ~/Sites/ ]; then
  mkdir ~/Sites/
fi

echo "Creating config file for Global-Env Valet driver"
cat << 'VALET' > ~/Sites/.valet-env.php
<?php

/**
 * global ENV vars
 * Requires custom ValetDriver
 * https://github.com/madsem/global-env-valet-driver
 **/

return [

	'*' => [
		'key' => 'value',
	],

];
VALET

echo "Creating ~/Code"
if [ ! -d ~/Code/ ]; then
  mkdir ~/Code/
fi

################################################################################
#
# macOS defaults
#
################################################################################
echo "Installing macOS Defaults"
source ~/.config/dotfiles/prefs/macos/.macdock
source ~/.config/dotfiles/prefs/macos/.macos


echo "You should restart your machine now and then continue with the setup."
